language: go
go_import_path: github.com/vntchain/go-vnt
sudo: false
notifications: always
matrix:
  include:
    - stage: Build & Test on linux go1.10.x
      os: linux
      dist: trusty
      sudo: required
      go: 1.10.x
      before_install:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf      
      script:
        - make all
        - go install -v ./cmd/gvnt
        - go test ./vnt/...
        - go test ./event/...
        - go test ./params/...
        - go test ./internal/...
        - go test ./cmd/abigen
        - go test ./cmd/bootnode
        - go test ./cmd/clef
        - go test ./cmd/vntkey
        - go test ./cmd/faucet
        - go test ./cmd/gvnt
        - go test ./cmd/p2psim
        - go test ./cmd/puppeth
        - go test ./cmd/rlpdump
        - go test ./cmd/utils
        - go test ./cmd/wnode
        - go test ./log/...
        - go test ./trie/...
        - go test ./miner/...
        - go test ./tests/...
        - go test ./rlp/...
        - go test ./accounts/...
        - go test ./rpc/...
        - go test ./common/...
        - go test ./consensus/...
        - go test ./mobile/...
        - go test ./crypto/...
        - go test ./bmt/...
        - go test ./vntstats/...
        - go test ./vntclient/...
        - go test ./signer/...
        - go test ./node/...
        - go test ./metrics/...
        - go test ./les/...
        - go test ./vntdb/...
        - go test ./core/...
        - go test ./light/...
        - go test ./console/...

    # These are the latest Go versions.
    - stage: Build & Test on linux go1.11.x
      if: branch = master
      os: linux
      dist: trusty
      sudo: required
      go: 1.11.x
      before_install:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf      
      script:
        - make all
        - go install -v ./cmd/gvnt
        - go test ./vnt/...
        - go test ./event/...
        - go test ./params/...
        - go test ./internal/...
        - go test ./cmd/abigen
        - go test ./cmd/bootnode
        - go test ./cmd/clef
        - go test ./cmd/vntkey
        - go test ./cmd/faucet
        - go test ./cmd/gvnt
        - go test ./cmd/p2psim
        - go test ./cmd/puppeth
        - go test ./cmd/rlpdump
        - go test ./cmd/utils
        - go test ./cmd/wnode
        - go test ./log/...
        - go test ./trie/...
        - go test ./miner/...
        - go test ./tests/...
        - go test ./rlp/...
        - go test ./accounts/...
        - go test ./rpc/...
        - go test ./common/...
        - go test ./consensus/...
        - go test ./mobile/...
        - go test ./crypto/...
        - go test ./bmt/...
        - go test ./vntstats/...
        - go test ./vntclient/...
        - go test ./signer/...
        - go test ./node/...
        - go test ./metrics/...
        - go test ./les/...
        - go test ./vntdb/...
        - go test ./core/...
        - go test ./light/...
        - go test ./console/...

    - stage: Build & Test on OSX
      if: branch = master
      os: osx
      go: 1.11.x
      before_install:
        - echo "Increase the maximum number of open file descriptors on macOS"
        - NOFILE=20480
        - sudo sysctl -w kern.maxfiles=$NOFILE
        - sudo sysctl -w kern.maxfilesperproc=$NOFILE
        - sudo launchctl limit maxfiles $NOFILE $NOFILE
        - sudo launchctl limit maxfiles
        - ulimit -S -n $NOFILE
        - ulimit -n
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
      script:              
        - make all
        - go install -v ./cmd/gvnt
        - go test ./vnt/...
        - go test ./event/...
        - go test ./params/...
        - go test ./internal/...
        - go test ./cmd/abigen
        - go test ./cmd/bootnode
        - go test ./cmd/clef
        - go test ./cmd/vntkey
        - go test ./cmd/faucet
        - go test ./cmd/gvnt
        - go test ./cmd/p2psim
        - go test ./cmd/puppeth
        - go test ./cmd/rlpdump
        - go test ./cmd/utils
        - go test ./cmd/wnode
        - go test ./log/...
        - go test ./trie/...
        - go test ./miner/...
        - go test ./tests/...
        - go test ./rlp/...
        - go test ./accounts/...
        - go test ./rpc/...
        - go test ./common/...
        - go test ./consensus/...
        - go test ./mobile/...
        - go test ./crypto/...
        - go test ./bmt/...
        - go test ./vntstats/...
        - go test ./vntclient/...
        - go test ./signer/...
        - go test ./node/...
        - go test ./metrics/...
        - go test ./les/...
        - go test ./vntdb/...
        - go test ./core/...
        - go test ./light/...
        - go test ./console/...
